### ISSUE TITLE
Provide Basic tutorial for getting Chat password.

### ISSUE THREAD

**Issue by tankerkiller125** [owenconti/livecodingtv-bot#1]
I have spent several hours trying to get my chat password/find out what it is. This is an issue for people using the new Oauth method of logging in,

**Comment by R4ver** [comment]
You can either use your own livecoding profile or create a new one for the bot. What ever you choose to do the password you have to use, is the one you log in with normally. Lets say you create an user for the bot on livecoding, then in the credentials.js the password you have to put in there is the password the bot uses.

Hope that helps.

**EDIT**
I was wrong about the password thing, but the Readme has been updated to explain how the "password" can be found.

**Comment by owenconti** [comment]
@tankerkiller125 can you read the README and let me know if it makes sense to find the password?
