### ISSUE TITLE
Bot Unexpectedly Crashed

### ISSUE THREAD

**Issue by kyledavi5** [owenconti/livecodingtv-bot#15]
This is the only occurrence that I've experienced thus far but I thought I'd document it for you guys. Here is the crash.
![Crash](https://i.gyazo.com/a86d80a149d53e8656d65e7f30d0f73c.png)

**Comment by owenconti** [comment]
hey @zultralord, thanks for reporting this.

Does this crash happen every time you run the bot?

**Comment by kyledavi5** [comment]
No I haven't been able to reproduce the error. I wouldn't say there is an issue here it just seemed like something you might want note on if others ever experience.
