### ISSUE TITLE
!help command not working

### ISSUE THREAD

**Issue by bretterer** [owenconti/livecodingtv-bot#16]
```
Command error:
{ name: '!help',
  help: 'Shows the documentation for core, plugins, and custom commands.',
  types: [ 'message' ],
  regex: /^(!|\/)(help|commands)$/,
  action: [Function] }
[TypeError: Cannot read property 'id' of null]
{
    "type": "message",
    "user": {
        "username": "lamarus",
        "role": "participant",
        "status": "Viewer",
        "viewCount": 1,
        "lastVisitTime": 1463240742689
    },
    "message": "!help",
    "rateLimited": false,
    "ranCommand": true
}
```

Other commands are working fine

**Comment by owenconti** [comment]
Can you try:
- stop the bot
- delete the help file from the brain directory
- restart the bot

**Comment by bretterer** [comment]
@owenconti there is no help file from the brain directory... on start of the server, I see this..

```
[Loader] Command loaded: ban-management
[Loader] Command loaded: custom-commands
[Loader] Command loaded: help
[Loader] Command loaded: leaderboard
[Loader] Command loaded: say
[Loader] Command loaded: subject
[Loader] Command loaded: todo
[Loader] Command loaded: user-status
[Loader] Command loaded: voices
WARNING: No /plugins directory exists.
[help] Generating help documentation
[help] Help documentation generated
[help] Creating new help documentation
[Gist] No Gist credentials, not creating a Gist!
Sat May 14 2016 12:50:02 GMT-0400 (EDT) Server is listening on port 8881
```

**Comment by owenconti** [comment]
Ah I see the problem. You haven't added your Gist credentials, so the help generation is failing. I need to add a fallback for that. 

I haven't used the bot since October, give me a few

**Comment by bretterer** [comment]
No problem... nowhere in the readme does it say anything about gist

Where do I  add these credentials?

**Comment by owenconti** [comment]
Okay I committed a hopeful fix to stop the crashing. The Gist creds should go in the credentials.js file, see this commit:

https://github.com/owenconti/livecodingtv-bot/commit/4769caeac5455053724f0d4a297abf99635414f3#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by bretterer** [comment]
Where exactly in the credentials.js file would it go... what you have here looks like json... however the credentials is a js file...

```
var username = 'lamarus'; // Your Livecoding.tv username
var password = 'XXXXXXX'; // Found in step 3
var room = 'lamarus'; // Room username

module.exports = {
    room: username,
    username: username,
    jid: username + '@livecoding.tv',
    password: password,
    roomJid: room + '@chat.livecoding.tv'
};
```

**Comment by bretterer** [comment]
Also.. Now I get this after doing a git pull

```
[Loader] Command loaded: ban-management
[Loader] Command loaded: custom-commands
[Loader] Command loaded: help
[Loader] Command loaded: leaderboard
[Loader] Command loaded: say
[Loader] Command loaded: subject
[Loader] Command loaded: todo
[Loader] Command loaded: user-status
[Loader] Command loaded: voices
WARNING: No /plugins directory exists.
[help] Generating help documentation
[help] Help documentation generated
[help] Creating new help documentation
[Gist] No Gist credentials, not creating a Gist!
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8881
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server.__dirname.Server.Server._listen2 (net.js:1230:14)
    at listen (net.js:1266:10)
    at Server.__dirname.Server.Server.listen (net.js:1362:5)
    at Websocket.startHttpServer (/Users/bretterer/lctv-bot/utils/Websocket.js:25:19)
    at Websocket.start (/Users/bretterer/lctv-bot/utils/Websocket.js:15:8)
    at /Users/bretterer/lctv-bot/utils/ChatBot.js:29:15
    at /Users/bretterer/lctv-bot/utils/Loader.js:73:5
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Comment by owenconti** [comment]
You have to add these two variables to that exports object:

```
"gistUsername" : "GIST_USERNAME",
"gistAccessToken" : "GIST_ACCESS_TOKEN"
```

Not sure about that error. Make sure there are no other running instances of the bot. Can also try: `ps aux | grep node` to see if there are any hidden processes

**Comment by owenconti** [comment]
Are you streaming right now?

**Comment by bretterer** [comment]
I am not... and the error was an issue of a bot running in another tab i didnt realize.

I added it in, is this what the help file gist should look like?

https://gist.github.com/bretterer/1b518e471eb4a532d93c40f290bc24a8

**Comment by owenconti** [comment]
That's better. But ideally there should be the basic commands in there. Hmmm..

**Comment by owenconti** [comment]
Was that all of it?

**Comment by bretterer** [comment]
All of what?  I am on IRC if you want to chat there instead of through comments   freenode user:lamarus

**Comment by owenconti** [comment]
Is this Gist (https://gist.github.com/bretterer/1b518e471eb4a532d93c40f290bc24a8) everything that was generated by the bot? Or was there more that you didn't copy/paste?

**Comment by owenconti** [comment]
pushed another fix. Can you pull and then restart the bot and then link me to the Gist?

**Comment by bretterer** [comment]
Looks like that did it... Thanks  https://gist.github.com/bretterer/1b518e471eb4a532d93c40f290bc24a8

**Comment by owenconti** [comment]
Thanks for trying the bot and reporting the issue.

**Comment by bretterer** [comment]
Thank you for making it.. I may have a few PR's coming your way once I get working with it
